BeautyBaseFinal/BeautyBaseFinal/Controllers/AvailablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeautyBaseFinal.Models;

namespace BeautyBaseFinal.Controllers
{

    [Authorize]
    public class AvailablesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Availables
        public ActionResult Index()
        {
            List<Available> availables = db.Availables.ToList();
            foreach (Available available in availables)
            {
                string[] selectedDate = available.Date.ToString().Split(' ')[0].Split('.');
                int selectedDay = Int32.Parse(selectedDate[0]);
                int selectedMonth = Int32.Parse(selectedDate[1]);
                int selectedYear = Int32.Parse(selectedDate[2]);
                int selectedHour = Int32.Parse(available.selectedTime.Split(':')[0]);
                int selectedMin = Int32.Parse(available.selectedTime.Split(':')[1]);
                string[] realDate1 = DateTime.Now.ToString("g").Split(' ');
                string[] realDate = realDate1[0].Split('.');
                int realDay = Int32.Parse(realDate[0]);
                int realMonth = Int32.Parse(realDate[1]);
                int realYear = Int32.Parse(realDate[2]);
                int realHour = Int32.Parse(realDate1[1].Split(':')[0]);
                int realMin = Int32.Parse(realDate1[1].Split(':')[1]);
                //dozvoluva prikaz samo na idni termini
                if (selectedYear < realYear || selectedYear == realYear && (selectedMonth < realMonth || selectedMonth == realMonth && (selectedDay < realDay || selectedDay == realDay && selectedHour < realHour|| (selectedHour==realHour&&selectedMin<realMin))))
                {

                    db.Availables.Remove(available);
                    db.SaveChanges();
                }

            }
            return View(db.Availables.ToList());
        }
    

        // GET: Availables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Available available = db.Availables.Find(id);
            if (available == null)
            {
                return HttpNotFound();
            }
            return View(available);
        }

        // GET: Availables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Availables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,selectedTime,Description")] Available available)
        {
            if (ModelState.IsValid)
            {
                string[] selectedDate = available.Date.ToString().Split(' ')[0].Split('.');
                int selectedDay = Int32.Parse(selectedDate[0]);
                int selectedMonth = Int32.Parse(selectedDate[1]);
                int selectedYear = Int32.Parse(selectedDate[2]);
                int selectedHour = Int32.Parse(available.selectedTime.Split(':')[0]);
                int selectedMin = Int32.Parse(available.selectedTime.Split(':')[1]);
                string[] realDate1 = DateTime.Now.ToString("g").Split(' ');
                string[] realDate = realDate1[0].Split('.');
                int realDay = Int32.Parse(realDate[0]);
                int realMonth = Int32.Parse(realDate[1]);
                int realYear = Int32.Parse(realDate[2]);
                int realHour = Int32.Parse(realDate1[1].Split(':')[0]);
                int realMin = Int32.Parse(realDate1[1].Split(':')[1]);
                //dozvoluva vnes samo na idni termini
                if (selectedYear < realYear || selectedYear == realYear && (selectedMonth < realMonth || selectedMonth == realMonth && selectedDay < realDay || (selectedDay==realDay&&selectedHour<realHour || (selectedHour==realHour&&selectedMin<realMin))))
                {

                    return RedirectToAction("Index");
                }
                else
                {
                    db.Availables.Add(available);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(available);
        }

        // GET: Availables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Available available = db.Availables.Find(id);
            if (available == null)
            {
                return HttpNotFound();
            }
            return View(available);
        }

        // POST: Availables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,selectedTime,Description")] Available available)
        {
            if (ModelState.IsValid)
            {
                db.Entry(available).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(available);
        }

        // GET: Availables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Available available = db.Availables.Find(id);
            if (available == null)
            {
                return HttpNotFound();
            }
            return View(available);
        }

        // POST: Availables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Available available = db.Availables.Find(id);
            db.Availables.Remove(available);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Reserve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Available available = db.Availables.Find(id);
            if (available == null)
            {
                return HttpNotFound();
            }
            return View(available);
        }

        // POST: Availables/Delete/5
        [HttpPost, ActionName("Reserve")]
        [ValidateAntiForgeryToken]
        public ActionResult ReserveConfirmed(int id)
        {
            Available available = db.Availables.Find(id);
            Unavailable unavailable = new Unavailable();
            unavailable.Date = available.Date;
            unavailable.selectedTime = available.selectedTime;
            unavailable.UserName = User.Identity.Name;
            unavailable.Description = available.Description;
            unavailable.ActionTime = DateTime.Now.ToString("g");
            db.Unavailables.Add(unavailable);
            db.Availables.Remove(available);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeautyBaseFinal/BeautyBaseFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeautyBaseFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BeautyBaseFinal/BeautyBaseFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BeautyBaseFinal/BeautyBaseFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Контакт</h2>
<h3 style="color:lightcoral">BeautyBase</h3>

<address>
    <img style="height:30px;" src="https://media.istockphoto.com/vectors/emailmail-icon-outline-vector-vector-id938581860?k=20&m=938581860&s=170667a&w=0&h=bDc6ZwtgdDqaKe08eUGsA22XjtU5cypCnX2ByvwsshU=" />
    beautybase@gmail.com
    <br />
    <img style="height:30px;" src="https://www.iconbunny.com/icons/media/catalog/product/1/6/168.1-phone-icon-iconbunny.jpg" />
    +38970111111
    <br />
    <img src="https://media.istockphoto.com/vectors/map-pin-vector-glyph-icon-vector-id1193451471?k=20&m=1193451471&s=612x612&w=0&h=ve7JRaMvw6L1HBiDOTVwfbhHALPPH-nCMCgG0Z_z5NY=" style="height:30px;" />
    ул. Метрополит Теодосиј Гологанов, Скопје<br />
</address>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2965.124993028711!2d21.396136814948086!3d41.9975929659078!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x135415481886757b%3A0x4fd9db475b11b555!2sImpeksel%20Domino!5e0!3m2!1smk!2smk!4v1633020271882!5m2!1smk!2smk" width="600px" height="450px" style="border:0px;" allowfullscreen="" loading="lazy"></iframe>
<address>
   </address>

BeautyBaseFinal/BeautyBaseFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<body style="background-color: #DCDCDC">
    <div style="height:1000px;">
        <h1>
            <span style="color: lightcoral">
                BeautyBase
            </span>
            <span>

                - најдобрата веб апликација за онлајн закажување!
            </span>
        </h1>
        <br />
        <br />
        <input id="add-new" onmouseover="over()" onmouseout="out()" style="background-color:lightcoral; border-style:none; border-radius:3px;  text-align:center; color: white; height:50px; width:150px;" type="button" value="Резервирај веднаш!" onclick="location.href='@Url.Action("Index", "Availables")'" />
        <br />
        <br />
        <br />
        <div>
            <div style="float: left; width:45%">
                <img src="https://media.allure.com/photos/60a41dbbab26bbb99a70cf3b/2:1/w_3000,h_1500,c_limit/nail%20salon.jpg" style="height:300px; " />
            </div>
            <div style=" float: right; width: 45%; height: 300px;">
                <br />
                <br>
                <b>
                    <p style="text-align: justify; ">
                        Нашиот салон нуди врвна услуга според највисоки светски стандарди. Задоволните клиенти се наш највисок приоритет
                        и мотивација за константно унапредување на целокупното искуство.
                    </p>
                </b>
            </div>
        </div>
        <br />
        <br />
        <br />
        <div>
            <div style="width: 45%; height: 300px; float: left;">
                <br />
                <br />
                <b>
                    <p style="text-align: justify; ">
                        BeautyBase ги почитува сите протоколи и мерки пропишани од страна на Владата на Република Северна Македонија. Исто така редовно ја следи
                        ситуацијата која се однесува на глобалната пандемија и во својот салон имплементира најнови техологии кои имаат за цел да го заштитат здравјето на клиентот.
                        ВАЖНО: Во салонот во еден термин е присутен само еден клиент, со цел да се спречи ширење на зараза од COVID-19.
                    </p>
                </b>
            </div>
            <div style="width: 45%; float: right">
                <img src="https://coronavirus.lacity.org/sites/g/files/wph1886/files/inline-images/five-ways-apr3.png" style="height:300px" />
            </div>
        </div>
    </div>
</body>
<script>
    function over() {
        document.getElementById("add-new").style.backgroundColor = 'coral';
    };
    function out() {
        document.getElementById("add-new").style.backgroundColor = 'lightcoral';
    }
</script>